{{- $services := list "content" "assessment" "tutor" "lab" "recommender" "community" -}}
{{- range $svc := $services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector: { matchLabels: { app: {{ $svc }} } }
  template:
    metadata: { labels: { app: {{ $svc }} } }
    spec:
      containers:
        - name: {{ $svc }}
          image: "{{ $.Values.image.repository }}/{{ $svc }}:{{ $.Values.image.tag }}"
          ports: [ { containerPort: 8000 } ]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc }}
spec:
  selector: { app: {{ $svc }} }
  ports: [ { port: 80, targetPort: 8000 } ]
{{- end }}
