# Default values for NEXUSA (production-grade)

image:
  repository: ghcr.io/nexus-aitech/nexusa
  tag: "1.0.0"
  pullPolicy: IfNotPresent

replicaCount: 3

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 2000
  readOnlyRootFilesystem: true

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: ${NEXUSA_HOST}
      paths:
        - /
  tls:
    - secretName: nexusa-tls
      hosts:
        - ${NEXUSA_HOST}

livenessProbe:
  httpGet:
    path: /live
    port: 8080
  initialDelaySeconds: 15
  timeoutSeconds: 2

readinessProbe:
  httpGet:
    path: /ready
    port: 8080
  initialDelaySeconds: 10
  timeoutSeconds: 2
