apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutor-deployment
  labels:
    app: tutor
    app.kubernetes.io/name: tutor
    app.kubernetes.io/part-of: nexusa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tutor
  template:
    metadata:
      labels:
        app: tutor
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      containers:
      - name: tutor-container
        image: ghcr.io/nexus-aitech/tutor:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: nexusa-secrets
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: tutor-service
spec:
  selector:
    app: tutor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
